In [1]:
import pandas as pd

In [7]:
finaldf = pd.read_csv('~/Documents/GitHub/FinalProjectLCA/data/cleaned/cleandf.csv', delimiter=';')

In [8]:
finaldf.head(5)

,account__id,date,SaldoInsoluto,days_late_at_date,customer_status_final
0,5daa2b82-f1ff-4f2d-a93e-5a6e887e50a2,2021-01-31,7773.888191,0,current
1,5df510ff-4850-42e0-ae7b-9f6cf07bc7a3,2021-01-31,4952.785658,0,current
2,5e30304e-648e-454f-9d4b-638144264ac4,2021-01-31,4084.748315,0,current
3,5e7959f1-aa3d-4010-9625-44bda535709f,2021-01-31,7470.341882,0,current
4,5f114ecd-4fb4-42e1-85ff-6049021a3b01,2021-01-31,1904.930000,0,current

In [83]:
finaldf.isna().sum()

account__id              0
date                     0
SaldoInsoluto            0
days_late_at_date        0
customer_status_final    0
dtype: int64

In [21]:
#finaldf[finaldf['customer_status_final'] == 'loss']

,account__id,date,SaldoInsoluto,days_late_at_date,customer_status_final
1458600,5eea39ca-0945-46be-911c-0ac42020588f,2021-08-31,2432.498557,182,loss
1714769,5fac2cfd-30ea-4e28-a2cd-6a60791633d5,2021-08-31,1791.439173,185,loss
1916515,5eea39ca-0945-46be-911c-0ac42020588f,2021-09-30,2796.330222,212,loss
2042873,600c340d-9dfa-43d1-9dff-58aee698a3d7,2021-09-30,1212.098150,188,loss
2234996,5fac2cfd-30ea-4e28-a2cd-6a60791633d5,2021-09-30,1989.601703,215,loss
...,...,...,...,...,...
30297043,624f5940-62ce-44b3-a137-a41f855e133e,2022-12-31,0.000000,192,loss
30297071,6256eb3f-d6cf-4de0-967f-e8e495e54e6d,2022-12-31,12757.191727,192,loss
30297080,62591c39-d429-490b-a54d-0e87b254504b,2022-12-31,0.000000,192,loss
30297126,62696843-956c-4dc9-9538-e602ca953d96,2022-12-31,0.000000,197,loss
30297183,627d2484-7e9b-48be-8aac-b8337b1adf1a,2022-12-31,0.000000,197,loss

In [27]:
#pruebadf = finaldf[finaldf['account__id'] == '5eea39ca-0945-46be-911c-0ac42020588f']

In [28]:
#pruebadf

,account__id,date,SaldoInsoluto,days_late_at_date,customer_status_final
27218,5eea39ca-0945-46be-911c-0ac42020588f,2021-01-31,2.841495e+03,0,current
101642,5eea39ca-0945-46be-911c-0ac42020588f,2021-02-28,5.479977e+02,0,current
191481,5eea39ca-0945-46be-911c-0ac42020588f,2021-03-31,8.338478e+02,29,current
364610,5eea39ca-0945-46be-911c-0ac42020588f,2021-04-30,1.129384e+03,59,current
364611,5eea39ca-0945-46be-911c-0ac42020588f,2021-04-30,1.129384e+03,59,current
613771,5eea39ca-0945-46be-911c-0ac42020588f,2021-05-31,1.436154e+03,90,pre-loss
826144,5eea39ca-0945-46be-911c-0ac42020588f,2021-06-30,1.755654e+03,120,pre-loss
1099600,5eea39ca-0945-46be-911c-0ac42020588f,2021-07-31,2.087614e+03,151,pre-loss
1458600,5eea39ca-0945-46be-911c-0ac42020588f,2021-08-31,2.432499e+03,182,loss
1916515,5eea39ca-0945-46be-911c-0ac42020588f,2021-09-30,2.796330e+03,212,loss
2491907,5eea39ca-0945-46be-911c-0ac42020588f,2021-10-31,5.455562e+02,0,loss
3226191,5eea39ca-0945-46be-911c-0ac42020588f,2021-11-30,5.479977e+02,0,loss
4144744,5eea39ca-0945-46be-911c-0ac42020588f,2021-12-31,5.479977e+02,0,loss
5240638,5eea39ca-0945-46be-911c-0ac42020588f,2022-01-31,5.400257e+02,28,loss
6522177,5eea39ca-0945-46be-911c-0ac42020588f,2022-02-28,-2.100000e-08,0,loss
8015190,5eea39ca-0945-46be-911c-0ac42020588f,2022-03-31,-2.100000e-08,0,loss
9832488,5eea39ca-0945-46be-911c-0ac42020588f,2022-05-31,-2.100000e-08,0,loss
12021491,5eea39ca-0945-46be-911c-0ac42020588f,2022-06-30,-2.100000e-08,0,loss
14379901,5eea39ca-0945-46be-911c-0ac42020588f,2022-07-31,-2.100000e-08,27,loss
16895113,5eea39ca-0945-46be-911c-0ac42020588f,2022-08-31,-2.100000e-08,58,loss
19577356,5eea39ca-0945-46be-911c-0ac42020588f,2022-09-30,-2.300000e-08,88,loss
22400752,5eea39ca-0945-46be-911c-0ac42020588f,2022-10-31,-2.300000e-08,119,loss
25338275,5eea39ca-0945-46be-911c-0ac42020588f,2022-11-30,-2.300000e-08,149,loss
28376823,5eea39ca-0945-46be-911c-0ac42020588f,2022-12-31,-2.300000e-08,180,loss

In [68]:
finaldf.customer_status_final = finaldf.customer_status_final.replace('current','0')
finaldf.customer_status_final = finaldf.customer_status_final.replace('pre-loss','1')
finaldf.customer_status_final = finaldf.customer_status_final.replace('loss','2')

In [69]:
finaldf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30297699 entries, 0 to 30297698
Data columns (total 5 columns):
 #   Column                 Dtype
---  ------                 -----
 0   account__id            object
 1   date                   object
 2   SaldoInsoluto          float64
 3   days_late_at_date      int64
 4   customer_status_final  object
dtypes: float64(1), int64(1), object(3)
memory usage: 1.1+ GB

In [70]:
finaldf.customer_status_final = finaldf.customer_status_final.astype('int64')

In [71]:
df_prueba_pivot = finaldf.pivot_table(index= 'account__id', columns=['date'], values=['days_late_at_date'],
                                       aggfunc="max")

df_prueba_pivot.head(10)

                                     days_late_at_date
date                                        2021-01-31 2021-02-28 2021-03-31
account__id
5d1bdad7-8431-4f8e-87dd-21147529d194               0.0        0.0        0.0  \
5d38cfc2-1913-4623-b1e7-44bcb6867d96               0.0        0.0        0.0
5d39f1ef-625c-43b3-970e-bdb28ac37bce               0.0        0.0        0.0
5d3a0d04-4170-45bd-9c43-e4401ce74279               0.0        0.0        0.0
5d3a0d84-faea-4d07-ad24-505ccb394e34               0.0        0.0        0.0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d             139.0      167.0        0.0
5d3a0f13-67a7-433d-af80-c4e4511338b3               0.0        0.0        0.0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856               0.0        0.0        0.0
5d3a1134-29f3-4915-b6fa-5d38e4246f38               0.0        0.0        0.0
5d3a1146-b375-4ee5-afa6-487760ae9787               0.0        0.0        0.0


date                                 2021-04-30 2021-05-31 2021-06-30
account__id
5d1bdad7-8431-4f8e-87dd-21147529d194        0.0        0.0        0.0  \
5d38cfc2-1913-4623-b1e7-44bcb6867d96        0.0        0.0        0.0
5d39f1ef-625c-43b3-970e-bdb28ac37bce        0.0        0.0        0.0
5d3a0d04-4170-45bd-9c43-e4401ce74279        0.0        0.0        0.0
5d3a0d84-faea-4d07-ad24-505ccb394e34        0.0        0.0        0.0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d        0.0        0.0        0.0
5d3a0f13-67a7-433d-af80-c4e4511338b3        0.0        0.0        0.0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856        0.0        0.0        0.0
5d3a1134-29f3-4915-b6fa-5d38e4246f38        0.0        0.0        0.0
5d3a1146-b375-4ee5-afa6-487760ae9787        0.0        0.0        0.0


date                                 2021-07-31 2021-08-31 2021-09-30
account__id
5d1bdad7-8431-4f8e-87dd-21147529d194        0.0        0.0        0.0  \
5d38cfc2-1913-4623-b1e7-44bcb6867d96        0.0        0.0        0.0
5d39f1ef-625c-43b3-970e-bdb28ac37bce        0.0        0.0        0.0
5d3a0d04-4170-45bd-9c43-e4401ce74279        0.0        0.0        0.0
5d3a0d84-faea-4d07-ad24-505ccb394e34        0.0        0.0        0.0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d        0.0        0.0        0.0
5d3a0f13-67a7-433d-af80-c4e4511338b3        0.0        0.0        0.0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856        0.0        0.0        0.0
5d3a1134-29f3-4915-b6fa-5d38e4246f38        0.0        0.0        0.0
5d3a1146-b375-4ee5-afa6-487760ae9787        0.0        0.0        0.0

                                                 ...
date                                 2021-10-31  ... 2022-02-28 2022-03-31
account__id                                      ...
5d1bdad7-8431-4f8e-87dd-21147529d194        0.0  ...        0.0        0.0  \
5d38cfc2-1913-4623-b1e7-44bcb6867d96        0.0  ...        0.0        0.0
5d39f1ef-625c-43b3-970e-bdb28ac37bce        0.0  ...        0.0        0.0
5d3a0d04-4170-45bd-9c43-e4401ce74279        0.0  ...        0.0        0.0
5d3a0d84-faea-4d07-ad24-505ccb394e34        0.0  ...        0.0        0.0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d        0.0  ...        0.0        0.0
5d3a0f13-67a7-433d-af80-c4e4511338b3        0.0  ...        0.0        0.0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856        0.0  ...        0.0        0.0
5d3a1134-29f3-4915-b6fa-5d38e4246f38        0.0  ...        0.0        0.0
5d3a1146-b375-4ee5-afa6-487760ae9787        0.0  ...        0.0        0.0


date                                 2022-05-31 2022-06-30 2022-07-31
account__id
5d1bdad7-8431-4f8e-87dd-21147529d194        0.0        0.0        0.0  \
5d38cfc2-1913-4623-b1e7-44bcb6867d96        0.0        0.0        0.0
5d39f1ef-625c-43b3-970e-bdb28ac37bce        0.0        0.0        0.0
5d3a0d04-4170-45bd-9c43-e4401ce74279        0.0        0.0        0.0
5d3a0d84-faea-4d07-ad24-505ccb394e34        0.0        0.0        0.0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d        0.0        0.0        0.0
5d3a0f13-67a7-433d-af80-c4e4511338b3        0.0        0.0        0.0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856        0.0        0.0        0.0
5d3a1134-29f3-4915-b6fa-5d38e4246f38        0.0        0.0        0.0
5d3a1146-b375-4ee5-afa6-487760ae9787        0.0        0.0        0.0


date                                 2022-08-31 2022-09-30 2022-10-31
account__id
5d1bdad7-8431-4f8e-87dd-21147529d194        0.0        0.0        0.0  \
5d38cfc2-1913-4623-b1e7-44bcb6867d96        0.0        0.0        0.0
5d39f1ef-625c-43b3-970e-bdb28ac37bce        0.0        0.0        0.0
5d3a0d04-4170-45bd-9c43-e4401ce74279        0.0        0.0        0.0
5d3a0d84-faea-4d07-ad24-505ccb394e34        0.0        0.0        0.0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d        0.0        0.0        0.0
5d3a0f13-67a7-433d-af80-c4e4511338b3        0.0        0.0        0.0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856        0.0        0.0        0.0
5d3a1134-29f3-4915-b6fa-5d38e4246f38        0.0        0.0        0.0
5d3a1146-b375-4ee5-afa6-487760ae9787        0.0        0.0        0.0


date                                 2022-11-30 2022-12-31
account__id
5d1bdad7-8431-4f8e-87dd-21147529d194        0.0        0.0
5d38cfc2-1913-4623-b1e7-44bcb6867d96        0.0        0.0
5d39f1ef-625c-43b3-970e-bdb28ac37bce        0.0        0.0
5d3a0d04-4170-45bd-9c43-e4401ce74279        0.0        0.0
5d3a0d84-faea-4d07-ad24-505ccb394e34        0.0        0.0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d        0.0        0.0
5d3a0f13-67a7-433d-af80-c4e4511338b3        0.0        0.0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856        0.0        0.0
5d3a1134-29f3-4915-b6fa-5d38e4246f38        0.0        0.0
5d3a1146-b375-4ee5-afa6-487760ae9787        0.0        0.0

[10 rows x 23 columns]

In [72]:
df_prueba_pivot = df_prueba_pivot.droplevel(0, axis=1)

In [73]:
extracol = finaldf[['account__id','customer_status_final']]

extracol.head(10)

                            account__id  customer_status_final
0  5daa2b82-f1ff-4f2d-a93e-5a6e887e50a2                      0
1  5df510ff-4850-42e0-ae7b-9f6cf07bc7a3                      0
2  5e30304e-648e-454f-9d4b-638144264ac4                      0
3  5e7959f1-aa3d-4010-9625-44bda535709f                      0
4  5f114ecd-4fb4-42e1-85ff-6049021a3b01                      0
5  5f2eecf2-fd1c-429c-a224-f5e9fca1e652                      0
6  5f3ff8bb-2772-4c82-b2e3-b6204d5652ec                      0
7  5f405411-d07b-4213-885d-8d6902c4a410                      0
8  5f430a8a-eef3-460b-935b-917ba7e86e4a                      0
9  5f596032-a460-4780-bb9a-1f3e85821008                      0

In [74]:
extracol.shape

(30297699, 2)

In [84]:
extracol.isna().sum()

account__id              0
customer_status_final    0
dtype: int64

In [75]:
custcol = extracol.groupby(by='account__id').max()

custcol.head(10)

                                      customer_status_final
account__id
5d1bdad7-8431-4f8e-87dd-21147529d194                      0
5d38cfc2-1913-4623-b1e7-44bcb6867d96                      0
5d39f1ef-625c-43b3-970e-bdb28ac37bce                      0
5d3a0d04-4170-45bd-9c43-e4401ce74279                      0
5d3a0d84-faea-4d07-ad24-505ccb394e34                      0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d                      1
5d3a0f13-67a7-433d-af80-c4e4511338b3                      0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856                      0
5d3a1134-29f3-4915-b6fa-5d38e4246f38                      0
5d3a1146-b375-4ee5-afa6-487760ae9787                      0

In [82]:
custcol.value_counts()

customer_status_final
0                        2649592
1                         364550
2                          80140
Name: count, dtype: int64

In [77]:
finaldata = custcol.merge(df_prueba_pivot, on='account__id')

finaldata.head(10)

,customer_status_final,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,...,2022-02-28,2022-03-31,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31
account__id,,,,,,,,,,,,,,,,,,,,,
5d1bdad7-8431-4f8e-87dd-21147529d194,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d38cfc2-1913-4623-b1e7-44bcb6867d96,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d39f1ef-625c-43b3-970e-bdb28ac37bce,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d3a0d04-4170-45bd-9c43-e4401ce74279,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d3a0d84-faea-4d07-ad24-505ccb394e34,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d3a0ea3-d50d-4714-809b-0089e05c0f0d,1,139.0,167.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d3a0f13-67a7-433d-af80-c4e4511338b3,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d3a0f87-0107-4f1b-94b8-a3717ff5b856,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d3a1134-29f3-4915-b6fa-5d38e4246f38,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5d3a1146-b375-4ee5-afa6-487760ae9787,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
finaldata.shape

(3094282, 24)

In [85]:
finaldata.isna().sum()

customer_status_final          0
2021-01-31               3024434
2021-02-28               3012469
2021-03-31               2991975
2021-04-30               2951773
2021-05-31               2900871
2021-06-30               2851364
2021-07-31               2771964
2021-08-31               2675262
2021-09-30               2573611
2021-10-31               2431318
2021-11-30               2244102
2021-12-31               2064882
2022-01-31               1889668
2022-02-28               1686398
2022-03-31               1460987
2022-05-31                974314
2022-06-30                791479
2022-07-31                644608
2022-08-31                470615
2022-09-30                314837
2022-10-31                197221
2022-11-30                 89144
2022-12-31                     0
dtype: int64

In [86]:
finaldata = finaldata.fillna(0)

In [87]:
finaldata.isna().sum()

customer_status_final    0
2021-01-31               0
2021-02-28               0
2021-03-31               0
2021-04-30               0
2021-05-31               0
2021-06-30               0
2021-07-31               0
2021-08-31               0
2021-09-30               0
2021-10-31               0
2021-11-30               0
2021-12-31               0
2022-01-31               0
2022-02-28               0
2022-03-31               0
2022-05-31               0
2022-06-30               0
2022-07-31               0
2022-08-31               0
2022-09-30               0
2022-10-31               0
2022-11-30               0
2022-12-31               0
dtype: int64

In [88]:
finaldata.to_csv('/Users/laura.chavez/Documents/GitHub/FinalProjectLCA/data/cleaned/totaldata.csv',sep=';')